# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_id',
            field=models.IntegerField(default=0),
        ),
    ]
