# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_u_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField(default=0)),
                ('follow', user.models.FollowListField()),
            ],
            options={
                'db_table': 'CMTwitter_follow',
            },
        ),
    ]
