# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follow',
            new_name='following',
        ),
    ]
