# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='author_name',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
