# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_status_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='author_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
